export type WAMessageType = 'text' | 'image' | 'video' | 'audio' | 'document' | 'sticker' | 'reaction' | 'location' | 'contact' | 'poll' | 'unknown'
export type WASessionStatus = 'connecting' | 'open' | 'close' | 'logout' | 'error' | 'timeout'
export type WAMessageStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'failed' | 'played'

export type IncomingMessageJob = {
    sessionId: string
    from: string
    to: string
    messageId: string
    fromMe: boolean
    type: WAMessageType
    content: string | null
    timestamp: number
    quotedMessageId?: string
    reactedMessagedId?: string
    pushName?: string
    status?: WAMessageStatus
    participant?: string
    // Added for media download
    mediaData?: any
}

export type OutgoingMessageContent =
    | { type: 'text'; text: string }
    | { type: 'image'; bucket: string; key: string; caption?: string }
    | { type: 'audio'; bucket: string; key: string; ptt?: boolean }
    | { type: 'video'; bucket: string; key: string; caption?: string }
    | { type: 'document'; bucket: string; key: string; mimetype: string; fileName: string }
    | { type: 'sticker'; bucket: string; key: string }
    | { type: 'reaction'; emoji: string; targetMessageId: string; targetFromMe: boolean }
    | { type: 'location'; latitude: number; longitude: number; name?: string; address?: string }

export type OutgoingMessageJob = {
    sessionId: string
    to: string
    content: OutgoingMessageContent
    quotedMessageId?: string
    messageUUID?: string // Local UUID generated by API
    agentId?: string // User ID of the agent who sent the message
}


export type ContactSyncJob = {
    sessionId: string
    contacts: {
        id: string
        phoneNumber?: string
        name?: string
        notify?: string
        verifiedName?: string
        imgUrl?: string
    }[]
}

export type ChatSyncJob = {
    sessionId: string
    chats: {
        id: string
        pnJid?: string
        name?: string
        unreadCount: number
        conversationTimestamp: number
        lastMessageRecvTimestamp?: number
        archived: boolean
        readOnly?: boolean
        notSpam?: boolean
        // last message data
        lastMessage?: {
            key: {
                remoteJid: string
                fromMe: boolean
                id: string
            }
            messageTimestamp: number
            content?: string
            type: WAMessageType
        }
    }[]
}

export type MessageSyncJob = {
    sessionId: string
    messages: {
        remoteJid: string
        fromMe: boolean
        messageId: string
        messageTimestamp: number
        type: WAMessageType
        content: string | null
        pushName?: string
        status?: WAMessageStatus
        quotedMessageId?: string
        participant?: string
        // Added for media download
        mediaData?: any
    }[]
}

export type MediaDownloadJob = {
    sessionId: string
    messageId: string // Local Database UUID of the message
    type: WAMessageType
    mediaData: any // Raw media message object from Baileys
}

export type SessionUpdateJob = {
    sessionId: string
    status: WASessionStatus
}

export type WebhookDispatchJob = {
    url: string
    secret: string
    payload: any // BREEventPayload[T]
    event: string // BREEventName
}

// packages/types/src/index.ts — tambahkan
export type StartSessionJob = {
    sessionId: string
}

export type StopSessionJob = {
    sessionId: string
    logout?: boolean
}

export type JobPayloads = {
    'incoming-message': IncomingMessageJob
    'outgoing-message': OutgoingMessageJob
    'contact-sync': ContactSyncJob
    'chat-sync': ChatSyncJob
    'message-sync': MessageSyncJob
    'media-download': MediaDownloadJob
    'session-update': SessionUpdateJob
    'start-session': StartSessionJob
    'stop-session': StopSessionJob
    'webhook-dispatch': WebhookDispatchJob
    'check-session-timeout': { sessionId: string }
}

export type JobName = keyof JobPayloads